-- Storage bucket for all story media. Objects are keyed as:
--   {story_id}/{slide_id}/{media_id}.{ext}          (originals)
--   {story_id}/{slide_id}/{media_id}_thumb.jpg       (thumbnails)
--   {story_id}/cover.{ext}                           (story cover)
-- The bucket is private; access goes through signed URLs generated by the app
-- for authenticated/member reads, and through the anon-readable policy below
-- only for stories that are actively shared via a public share link.

insert into storage.buckets (id, name, public)
values ('story-media', 'story-media', false)
on conflict (id) do nothing;

create policy "members read story media objects"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'story-media'
    and public.is_story_member((storage.foldername(name))[1]::uuid, 'viewer')
  );

create policy "anonymous read public story media objects"
  on storage.objects for select
  to anon
  using (
    bucket_id = 'story-media'
    and public.is_story_public((storage.foldername(name))[1]::uuid)
  );

create policy "editors upload story media objects"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'story-media'
    and public.is_story_member((storage.foldername(name))[1]::uuid, 'editor')
  );

create policy "editors update story media objects"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'story-media'
    and public.is_story_member((storage.foldername(name))[1]::uuid, 'editor')
  )
  with check (
    bucket_id = 'story-media'
    and public.is_story_member((storage.foldername(name))[1]::uuid, 'editor')
  );

create policy "editors delete story media objects"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'story-media'
    and public.is_story_member((storage.foldername(name))[1]::uuid, 'editor')
  );
